# Generated by Django 6.0.6 on 2026-07-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
